/**
 * Layer 0 - Tool Auto-Repair
 * 
 * Intercepts tool call failures and attempts automatic fixes:
 * - Missing script files → Create them
 * - Missing npm packages → Install them
 * - Missing directories → Create them
 * - Permission errors → Suggest fixes
 * 
 * This is TRUE self-repair at the tool execution level.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { dirname, join } from 'node:path'

// ============================================
// Types
// ============================================

export interface ToolResult {
    success?: boolean
    error?: string
    action?: string
    missingFile?: string
    originalCommand?: string
    [key: string]: unknown
}

export interface RepairResult {
    repaired: boolean
    action: string
    details: string
    shouldRetry: boolean
    fixedResult?: unknown
}

export interface RepairStats {
    totalAttempts: number
    successfulRepairs: number
    failedRepairs: number
    repairsByType: Record<string, number>
}

// ============================================
// Repair Patterns
// ============================================

interface RepairPattern {
    name: string
    detect: (result: ToolResult, toolName: string, params: Record<string, unknown>) => boolean
    repair: (result: ToolResult, toolName: string, params: Record<string, unknown>) => Promise<RepairResult>
}

const REPAIR_PATTERNS: RepairPattern[] = [
    // Pattern 1: Missing script file
    {
        name: 'missing_script_file',
        detect: (result) => {
            return Boolean(
                result.action === 'CREATE_FILE_FIRST' ||
                (result.error?.includes('Script') && result.error?.includes('nicht gefunden')) ||
                result.error?.includes('Cannot find module') ||
                result.error?.includes('ENOENT')
            )
        },
        repair: async (result, _toolName, params) => {
            const missingFile = result.missingFile as string
            const command = (result.originalCommand || params.command) as string

            if (!missingFile) {
                return {
                    repaired: false,
                    action: 'missing_script_file',
                    details: 'Konnte Dateipfad nicht ermitteln',
                    shouldRetry: false,
                }
            }

            // Determine file type and create basic template
            const ext = missingFile.split('.').pop()?.toLowerCase()
            let content = ''

            switch (ext) {
                case 'js':
                    content = `// Auto-generated by Nova Layer 0 Self-Repair
// This file was created because it was missing when trying to run: ${command}
// Please replace this content with your actual code.

console.log('Script created by Nova - please add your code here');
`
                    break
                case 'ts':
                    content = `// Auto-generated by Nova Layer 0 Self-Repair
// TypeScript file created for: ${command}

console.log('TypeScript script created by Nova');
`
                    break
                case 'py':
                    content = `# Auto-generated by Nova Layer 0 Self-Repair
# Python file created for: ${command}

print('Python script created by Nova - please add your code')
`
                    break
                default:
                    content = `// Auto-generated placeholder by Nova Layer 0\n`
            }

            try {
                // Create directory if needed
                const dir = dirname(missingFile)
                if (!existsSync(dir)) {
                    mkdirSync(dir, { recursive: true })
                }

                // Create the file
                writeFileSync(missingFile, content)
                console.log(`[L0 AutoRepair] ✅ Created missing file: ${missingFile}`)

                return {
                    repaired: true,
                    action: 'missing_script_file',
                    details: `Datei erstellt: ${missingFile}`,
                    shouldRetry: true,
                }
            } catch (err) {
                return {
                    repaired: false,
                    action: 'missing_script_file',
                    details: `Konnte Datei nicht erstellen: ${err}`,
                    shouldRetry: false,
                }
            }
        },
    },

    // Pattern 2: Missing npm package
    {
        name: 'missing_npm_package',
        detect: (result) => {
            const error = result.error || ''
            return Boolean(
                error.includes('Cannot find module') ||
                error.includes('MODULE_NOT_FOUND') ||
                error.includes('is not recognized') ||
                (error.includes('npm') && error.includes('ERR!'))
            )
        },
        repair: async (result) => {
            const error = result.error || ''

            // Try to extract package name
            const moduleMatch = error.match(/Cannot find module ['"]([^'"]+)['"]/)
            if (!moduleMatch) {
                return {
                    repaired: false,
                    action: 'missing_npm_package',
                    details: 'Konnte Paketname nicht ermitteln',
                    shouldRetry: false,
                }
            }

            const packageName = moduleMatch[1]

            // Skip built-in modules
            if (['fs', 'path', 'http', 'https', 'crypto', 'os', 'child_process'].includes(packageName)) {
                return {
                    repaired: false,
                    action: 'missing_npm_package',
                    details: `${packageName} ist ein eingebautes Node.js Modul`,
                    shouldRetry: false,
                }
            }

            try {
                console.log(`[L0 AutoRepair] 📦 Installing missing package: ${packageName}`)
                execSync(`npm install ${packageName}`, {
                    encoding: 'utf-8',
                    timeout: 60000,
                    stdio: 'pipe',
                })

                return {
                    repaired: true,
                    action: 'missing_npm_package',
                    details: `Package installiert: ${packageName}`,
                    shouldRetry: true,
                }
            } catch (err) {
                return {
                    repaired: false,
                    action: 'missing_npm_package',
                    details: `npm install fehlgeschlagen: ${err}`,
                    shouldRetry: false,
                }
            }
        },
    },

    // Pattern 3: Missing directory
    {
        name: 'missing_directory',
        detect: (result) => {
            const error = result.error || ''
            return Boolean(
                error.includes('ENOENT') ||
                error.includes('no such file or directory') ||
                error.includes('Verzeichnis nicht gefunden')
            )
        },
        repair: async (result, _toolName, params) => {
            const path = params.path as string || params.cwd as string

            if (!path) {
                return {
                    repaired: false,
                    action: 'missing_directory',
                    details: 'Konnte Pfad nicht ermitteln',
                    shouldRetry: false,
                }
            }

            try {
                const dir = path.includes('.') ? dirname(path) : path
                mkdirSync(dir, { recursive: true })
                console.log(`[L0 AutoRepair] 📁 Created missing directory: ${dir}`)

                return {
                    repaired: true,
                    action: 'missing_directory',
                    details: `Verzeichnis erstellt: ${dir}`,
                    shouldRetry: true,
                }
            } catch (err) {
                return {
                    repaired: false,
                    action: 'missing_directory',
                    details: `Konnte Verzeichnis nicht erstellen: ${err}`,
                    shouldRetry: false,
                }
            }
        },
    },
]

// ============================================
// Tool Auto-Repair Engine
// ============================================

class ToolAutoRepairEngine {
    private stats: RepairStats = {
        totalAttempts: 0,
        successfulRepairs: 0,
        failedRepairs: 0,
        repairsByType: {},
    }
    private readonly MAX_RETRIES = 3

    /**
     * Attempt to repair a failed tool call and retry
     */
    async repairAndRetry(
        toolName: string,
        params: Record<string, unknown>,
        result: ToolResult,
        retryFn: (params: Record<string, unknown>) => Promise<unknown>,
        attempt: number = 1
    ): Promise<{ result: unknown; wasRepaired: boolean; repairDetails?: string }> {
        // Check if this looks like an error that needs repair
        if (result.success || (!result.error && !result.action)) {
            return { result, wasRepaired: false }
        }

        if (attempt > this.MAX_RETRIES) {
            console.log(`[L0 AutoRepair] ❌ Max retries (${this.MAX_RETRIES}) reached for ${toolName}`)

            // Trigger L8 Sub-Agent fallback
            try {
                const { getSubAgentManager } = await import('./L8-sub-agent.js')
                const manager = getSubAgentManager()
                const errorMsg = result.error || 'Unknown error'
                const problem = `${toolName} fehlgeschlagen: ${errorMsg}`

                // Spawn the sub-agent in background
                const noopReportFn = async (msg: string) => console.log(`[L8 Report] ${msg}`)
                const tryWithSolution = async (solution: string) => {
                    // Use solution as a hint to retry with modified params
                    console.log(`[L8] Trying solution: ${solution.slice(0, 50)}...`)
                    return retryFn(params)
                }
                await manager.spawnSearchAgent(
                    {
                        problem,
                        tool: toolName,
                        params,
                    },
                    tryWithSolution,
                    noopReportFn
                )

                console.log(`[L0→L8] 🔍 Sub-Agent gestartet für: ${problem.slice(0, 50)}...`)

                // Return with L8 message so Nova can tell user
                return {
                    result: {
                        ...result,
                        l8_fallback: true,
                        l8_message: manager.getFallbackMessage()
                    },
                    wasRepaired: false,
                    repairDetails: 'L8 Sub-Agent gestartet'
                }
            } catch (err) {
                console.log(`[L0 AutoRepair] L8 fallback not available: ${err}`)
            }

            return { result, wasRepaired: false }
        }


        this.stats.totalAttempts++

        // Find matching repair pattern
        for (const pattern of REPAIR_PATTERNS) {
            if (pattern.detect(result, toolName, params)) {
                console.log(`[L0 AutoRepair] 🔧 Detected pattern: ${pattern.name}`)

                const repairResult = await pattern.repair(result, toolName, params)

                if (repairResult.repaired) {
                    this.stats.successfulRepairs++
                    this.stats.repairsByType[pattern.name] = (this.stats.repairsByType[pattern.name] || 0) + 1

                    if (repairResult.shouldRetry) {
                        console.log(`[L0 AutoRepair] 🔄 Retrying ${toolName} after repair (attempt ${attempt + 1})`)

                        try {
                            const retryResult = await retryFn(params)

                            // Check if retry also failed
                            if (retryResult && typeof retryResult === 'object' && 'error' in retryResult) {
                                // Recursive repair attempt
                                return this.repairAndRetry(
                                    toolName,
                                    params,
                                    retryResult as ToolResult,
                                    retryFn,
                                    attempt + 1
                                )
                            }

                            return {
                                result: retryResult,
                                wasRepaired: true,
                                repairDetails: repairResult.details,
                            }
                        } catch (err) {
                            console.log(`[L0 AutoRepair] ❌ Retry failed: ${err}`)
                        }
                    }

                    return {
                        result: {
                            ...result,
                            repaired: true,
                            repairAction: repairResult.action,
                            repairDetails: repairResult.details,
                        },
                        wasRepaired: true,
                        repairDetails: repairResult.details,
                    }
                } else {
                    this.stats.failedRepairs++
                }
            }
        }

        return { result, wasRepaired: false }
    }

    /**
     * Wrap a tool handler with auto-repair capability
     */
    wrapToolHandler(
        toolName: string,
        handler: (params: Record<string, unknown>) => Promise<unknown>
    ): (params: Record<string, unknown>) => Promise<unknown> {
        return async (params: Record<string, unknown>) => {
            const result = await handler(params)

            // Check if result indicates failure
            if (result && typeof result === 'object' && ('error' in result || 'action' in result)) {
                const { result: repairedResult, wasRepaired, repairDetails } = await this.repairAndRetry(
                    toolName,
                    params,
                    result as ToolResult,
                    handler
                )

                if (wasRepaired) {
                    console.log(`[L0 AutoRepair] ✅ Tool ${toolName} repaired: ${repairDetails}`)
                }

                return repairedResult
            }

            return result
        }
    }

    getStats(): RepairStats {
        return { ...this.stats }
    }
}

// ============================================
// Singleton
// ============================================

let instance: ToolAutoRepairEngine | null = null

export function getToolAutoRepairEngine(): ToolAutoRepairEngine {
    if (!instance) {
        instance = new ToolAutoRepairEngine()
        console.log('[L0 AutoRepair] ✅ Tool Auto-Repair Engine initialized')
    }
    return instance
}

export default {
    ToolAutoRepairEngine,
    getToolAutoRepairEngine,
    REPAIR_PATTERNS,
}
