/**
 * Nova - Learning Engine
 * 
 * Unified self-improvement system that combines:
 * - Feedback Collection
 * - Pattern Detection
 * - Skill Generation
 * 
 * This is the brain that makes Nova smarter over time.
 */

import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { join } from 'node:path'

import { FeedbackCollector, type Feedback, type FeedbackType } from './feedback.js'
import { PatternDetector, type Pattern, type PatternCategory } from './patterns.js'
import { SkillGenerator, type Skill } from './skills.js'

// ============================================
// Types
// ============================================

export interface LearningConfig {
    dataDir: string                    // Where to store learning data
    autoLearnThreshold: number         // Min frequency before auto-generating skill
    patternConfidenceThreshold: number // Min confidence to use pattern response
    persistInterval: number            // Auto-save interval in ms (0 = disabled)
}

export interface LearningStats {
    feedback: {
        total: number
        corrections: number
        positive: number
        negative: number
    }
    patterns: {
        total: number
        highConfidence: number
    }
    skills: {
        total: number
        autoGenerated: number
        avgSuccessRate: number
    }
}

export interface LearnedResponse {
    response: string
    source: 'correction' | 'pattern' | 'skill'
    confidence: number
    skillId?: string
    patternId?: string
}

// ============================================
// Learning Engine Class
// ============================================

export class LearningEngine {
    private feedback: FeedbackCollector
    private patterns: PatternDetector
    private skills: SkillGenerator
    private config: LearningConfig
    private persistTimer?: NodeJS.Timeout
    private lastBotResponses = new Map<string, string>()

    constructor(config: Partial<LearningConfig> = {}) {
        this.config = {
            dataDir: '.nova-learning',
            autoLearnThreshold: 3,
            patternConfidenceThreshold: 0.7,
            persistInterval: 60000, // 1 minute
            ...config,
        }

        this.feedback = new FeedbackCollector()
        this.patterns = new PatternDetector()
        this.skills = new SkillGenerator()
    }

    // ============================================
    // Lifecycle
    // ============================================

    async start(): Promise<void> {
        console.log('[Nova Learning] Starting engine...')

        // Load persisted data
        await this.load()

        // Start auto-persist timer
        if (this.config.persistInterval > 0) {
            this.persistTimer = setInterval(() => {
                this.persist().catch(console.error)
            }, this.config.persistInterval)
        }

        const stats = this.getStats()
        console.log(`[Nova Learning] Engine started: ${stats.feedback.total} feedback, ${stats.patterns.total} patterns, ${stats.skills.total} skills`)
    }

    async stop(): Promise<void> {
        console.log('[Nova Learning] Stopping engine...')

        if (this.persistTimer) {
            clearInterval(this.persistTimer)
        }

        await this.persist()
        console.log('[Nova Learning] Engine stopped')
    }

    // ============================================
    // Message Processing
    // ============================================

    /**
     * Process incoming user message
     * Returns a learned response if available
     */
    processUserMessage(message: string, context?: { channel?: string; userId?: string }): LearnedResponse | null {
        // 1. Check for feedback in the message
        const feedbackType = this.feedback.detectFeedbackType(message)
        if (feedbackType) {
            this.handleFeedback(feedbackType, message, context)
        }

        // 2. Check for direct correction response
        const correctionResponse = this.feedback.getLearnedResponse(message, context?.userId)
        if (correctionResponse) {
            return {
                response: correctionResponse,
                source: 'correction',
                confidence: 0.9,
            }
        }

        // 3. Check for matching skill
        const skill = this.skills.findSkillForMessage(message)
        if (skill && skill.successRate >= this.config.patternConfidenceThreshold) {
            const response = this.skills.executeSkill(skill)
            return {
                response,
                source: 'skill',
                confidence: skill.successRate,
                skillId: skill.id,
            }
        }

        // 4. Check for matching pattern with response
        const pattern = this.patterns.findPatternForMessage(message)
        if (pattern && pattern.response && pattern.confidence >= this.config.patternConfidenceThreshold) {
            return {
                response: pattern.response,
                source: 'pattern',
                confidence: pattern.confidence,
                patternId: pattern.id,
            }
        }

        // 5. Process pattern for future learning
        const detectedPattern = this.patterns.processMessage(message)
        if (detectedPattern && detectedPattern.frequency >= this.config.autoLearnThreshold) {
            // Auto-generate skill from pattern
            this.skills.generateFromPattern(detectedPattern)
        }

        return null
    }

    /**
     * Record bot response (for feedback tracking)
     */
    recordBotResponse(response: string, context?: { channel?: string; userId?: string }): void {
        this.lastBotResponses.set(context?.userId || 'global', response)
    }

    // ============================================
    // Feedback Handling
    // ============================================

    private handleFeedback(type: FeedbackType, message: string, context?: { channel?: string; userId?: string }): void {
        // Extract correction if present
        let correction: string | undefined

        if (type === 'correction') {
            // Try to extract correction from message
            const patterns = [
                /eigentlich\s*(?:ist|war|sollte)?\s*(.+)/i,
                /richtig\s*(?:ist|wäre)?\s*[:.]?\s*(.+)/i,
                /korrektur\s*[:.]?\s*(.+)/i,
                /nein,?\s*(.+)/i,
            ]

            for (const pattern of patterns) {
                const match = message.match(pattern)
                if (match?.[1]) {
                    correction = match[1].trim()
                    break
                }
            }
        }

        this.feedback.collectFeedback({
            type,
            userMessage: message,
            botResponse: this.lastBotResponses.get(context?.userId || 'global') || '',
            correction,
            ...context,
        })
    }

    // ============================================
    // Manual Teaching
    // ============================================

    /**
     * Teach Nova a new response for a trigger
     */
    teach(trigger: string, response: string): Skill {
        return this.skills.createManualSkill({
            name: `Taught: ${trigger.slice(0, 30)}`,
            description: 'Manually taught response',
            triggers: [trigger.toLowerCase()],
            responseTemplate: response,
        })
    }

    /**
     * Set response for existing pattern
     */
    setPatternResponse(patternId: string, response: string): boolean {
        return this.patterns.setPatternResponse(patternId, response)
    }

    /**
     * Provide feedback for a skill
     */
    rateSkill(skillId: string, positive: boolean): void {
        this.skills.recordSkillFeedback(skillId, positive)
    }

    // ============================================
    // Statistics
    // ============================================

    getStats(): LearningStats {
        const feedbackStats = this.feedback.getStats()
        const patternStats = this.patterns.getStats()
        const skillStats = this.skills.getStats()

        return {
            feedback: {
                total: feedbackStats.total,
                corrections: feedbackStats.corrections,
                positive: feedbackStats.positive,
                negative: feedbackStats.negative,
            },
            patterns: {
                total: patternStats.totalPatterns,
                highConfidence: patternStats.highConfidence,
            },
            skills: {
                total: skillStats.totalSkills,
                autoGenerated: skillStats.autoGenerated,
                avgSuccessRate: skillStats.avgSuccessRate,
            },
        }
    }

    // ============================================
    // Data Access
    // ============================================

    getAllPatterns(): Pattern[] {
        return this.patterns.getAllPatterns()
    }

    getAllSkills(): Skill[] {
        return this.skills.getAllSkills()
    }

    getAllFeedback(): Feedback[] {
        return this.feedback.getAllFeedback()
    }

    // ============================================
    // Persistence
    // ============================================

    async persist(): Promise<void> {
        try {
            await mkdir(this.config.dataDir, { recursive: true })

            await Promise.all([
                writeFile(
                    join(this.config.dataDir, 'feedback.json'),
                    this.feedback.exportToJSON()
                ),
                writeFile(
                    join(this.config.dataDir, 'patterns.json'),
                    this.patterns.exportToJSON()
                ),
                writeFile(
                    join(this.config.dataDir, 'skills.json'),
                    this.skills.exportToJSON()
                ),
            ])

            console.log('[Nova Learning] Data persisted')
        } catch (err) {
            console.error('[Nova Learning] Persist failed:', err)
        }
    }

    async load(): Promise<void> {
        try {
            const [feedbackData, patternsData, skillsData] = await Promise.all([
                readFile(join(this.config.dataDir, 'feedback.json'), 'utf-8').catch(() => null),
                readFile(join(this.config.dataDir, 'patterns.json'), 'utf-8').catch(() => null),
                readFile(join(this.config.dataDir, 'skills.json'), 'utf-8').catch(() => null),
            ])

            if (feedbackData) this.feedback.importFromJSON(feedbackData)
            if (patternsData) this.patterns.importFromJSON(patternsData)
            if (skillsData) this.skills.importFromJSON(skillsData)

            console.log('[Nova Learning] Data loaded')
        } catch (err) {
            console.log('[Nova Learning] No existing data found, starting fresh')
        }
    }
}

// ============================================
// Factory
// ============================================

export function createLearningEngine(config?: Partial<LearningConfig>): LearningEngine {
    return new LearningEngine(config)
}

// ============================================
// Re-exports
// ============================================

export { FeedbackCollector, PatternDetector, SkillGenerator }
export type { Feedback, FeedbackType, Pattern, PatternCategory, Skill }

export default {
    LearningEngine,
    createLearningEngine,
    FeedbackCollector,
    PatternDetector,
    SkillGenerator,
}
