/**
 * Nova - Skill Generator
 * 
 * Automatically generates skills from detected patterns
 * Creates reusable response templates and action handlers
 */

import { randomUUID } from 'node:crypto'
import type { Pattern, PatternCategory } from './patterns.js'

// ============================================
// Types
// ============================================

export interface Skill {
    id: string
    name: string
    description: string
    category: PatternCategory

    // Triggers
    triggers: string[]           // Patterns that activate this skill
    triggerRegex?: RegExp        // Compiled regex for matching

    // Response
    responseTemplate: string     // Template with {variables}

    // Metadata
    autoGenerated: boolean       // Was this auto-generated?
    usageCount: number
    successRate: number          // 0-1 based on feedback

    createdAt: number
    updatedAt: number
}

export interface GeneratedSkillResult {
    skill: Skill
    isNew: boolean
    updatedFrom?: string         // ID of previous version
}

// ============================================
// Skill Templates
// ============================================

const CATEGORY_TEMPLATES: Record<PatternCategory, (pattern: Pattern) => string> = {
    question: (p) => `Basierend auf meinen Beobachtungen:\n\n${p.response ?? "Ich kann diese Frage beantworten."}`,

    command: (p) => `Ich führe diese Aufgabe aus:\n\n${p.response ?? "Erledigt!"}`,

    greeting: (_p) => {
        const greetings = ['Hallo!', 'Hi!', 'Hey!', 'Servus!', 'Guten Tag!']
        return greetings[Math.floor(Math.random() * greetings.length)] + ' Wie kann ich dir helfen?'
    },

    preference: (p) => `Ich habe mir gemerkt: ${p.response ?? p.pattern}`,

    correction: (p) => `Danke für die Korrektur! Ich merke mir: ${p.response ?? ""}`,

    task: (p) => `Ich helfe dir gerne dabei:\n\n${p.response ?? "Was genau brauchst du?"}`,

    other: (p) => p.response ?? 'Ich verstehe.',
}

// ============================================
// Skill Generator Class
// ============================================

export class SkillGenerator {
    private skills: Map<string, Skill> = new Map()
    private skillsByTrigger: Map<string, string> = new Map()  // trigger → skillId

    // ============================================
    // Generation
    // ============================================

    generateFromPattern(pattern: Pattern): GeneratedSkillResult {
        // Check if skill already exists for this pattern
        const existingSkillId = this.skillsByTrigger.get(pattern.pattern)
        if (existingSkillId) {
            const existingSkill = this.skills.get(existingSkillId)
            if (existingSkill) {
                // Update existing skill
                existingSkill.triggers = [...new Set([...existingSkill.triggers, pattern.pattern])]
                existingSkill.usageCount = pattern.frequency
                existingSkill.updatedAt = Date.now()

                if (pattern.response) {
                    existingSkill.responseTemplate = pattern.response
                }

                console.log(`[Nova Skills] Updated skill: ${existingSkill.name}`)
                return { skill: existingSkill, isNew: false, updatedFrom: existingSkillId }
            }
        }

        // Create new skill
        const skill = this.createSkillFromPattern(pattern)
        this.skills.set(skill.id, skill)

        // Map all triggers to this skill
        for (const trigger of skill.triggers) {
            this.skillsByTrigger.set(trigger, skill.id)
        }

        console.log(`[Nova Skills] Generated new skill: ${skill.name} (category: ${skill.category})`)
        return { skill, isNew: true }
    }

    private createSkillFromPattern(pattern: Pattern): Skill {
        const template = CATEGORY_TEMPLATES[pattern.category]

        return {
            id: randomUUID(),
            name: this.generateSkillName(pattern),
            description: `Auto-generated from pattern: "${pattern.pattern.slice(0, 50)}..."`,
            category: pattern.category,

            triggers: [pattern.pattern, ...pattern.examples.slice(0, 5).map(e =>
                e.toLowerCase().replace(/[^\w\säöüß]/g, '').trim()
            )],

            responseTemplate: template(pattern),

            autoGenerated: true,
            usageCount: pattern.frequency,
            successRate: pattern.confidence,

            createdAt: Date.now(),
            updatedAt: Date.now(),
        }
    }

    private generateSkillName(pattern: Pattern): string {
        const prefix = {
            question: 'Antwort',
            command: 'Aktion',
            greeting: 'Begrüßung',
            preference: 'Präferenz',
            correction: 'Korrektur',
            task: 'Aufgabe',
            other: 'Skill',
        }[pattern.category]

        const words = pattern.pattern.split(/\s+/).slice(0, 3).join(' ')
        return `${prefix}: ${words}`
    }

    // ============================================
    // Skill Execution
    // ============================================

    findSkillForMessage(message: string): Skill | null {
        const normalized = message.toLowerCase().replace(/[^\w\säöüß]/g, '').trim()

        // Check direct trigger match
        const skillId = this.skillsByTrigger.get(normalized)
        if (skillId) {
            return this.skills.get(skillId) ?? null
        }

        // Fuzzy search
        for (const skill of this.skills.values()) {
            for (const trigger of skill.triggers) {
                if (this.fuzzyMatch(normalized, trigger)) {
                    return skill
                }
            }
        }

        return null
    }

    executeSkill(skill: Skill, context?: Record<string, string>): string {
        skill.usageCount++
        skill.updatedAt = Date.now()

        let response = skill.responseTemplate

        // Replace variables in template
        if (context) {
            for (const [key, value] of Object.entries(context)) {
                response = response.replace(new RegExp(`\\{${key}\\}`, 'g'), value)
            }
        }

        return response
    }

    recordSkillFeedback(skillId: string, positive: boolean): void {
        const skill = this.skills.get(skillId)
        if (!skill) return

        // Update success rate (exponential moving average)
        const alpha = 0.2
        skill.successRate = alpha * (positive ? 1 : 0) + (1 - alpha) * skill.successRate
        skill.updatedAt = Date.now()
    }

    // ============================================
    // Helpers
    // ============================================

    private fuzzyMatch(a: string, b: string): boolean {
        if (a === b) return true
        if (a.length < 5 || b.length < 5) return false

        // Simple containment check
        return a.includes(b) || b.includes(a)
    }

    // ============================================
    // Management
    // ============================================

    createManualSkill(params: {
        name: string
        description: string
        triggers: string[]
        responseTemplate: string
        category?: PatternCategory
    }): Skill {
        const skill: Skill = {
            id: randomUUID(),
            name: params.name,
            description: params.description,
            category: params.category ?? 'other',
            triggers: params.triggers,
            responseTemplate: params.responseTemplate,
            autoGenerated: false,
            usageCount: 0,
            successRate: 0.8,
            createdAt: Date.now(),
            updatedAt: Date.now(),
        }

        this.skills.set(skill.id, skill)
        for (const trigger of skill.triggers) {
            this.skillsByTrigger.set(trigger.toLowerCase(), skill.id)
        }

        console.log(`[Nova Skills] Created manual skill: ${skill.name}`)
        return skill
    }

    deleteSkill(skillId: string): boolean {
        const skill = this.skills.get(skillId)
        if (!skill) return false

        // Remove trigger mappings
        for (const trigger of skill.triggers) {
            this.skillsByTrigger.delete(trigger)
        }

        this.skills.delete(skillId)
        console.log(`[Nova Skills] Deleted skill: ${skill.name}`)
        return true
    }

    getAllSkills(): Skill[] {
        return Array.from(this.skills.values())
    }

    getAutoGeneratedSkills(): Skill[] {
        return this.getAllSkills().filter(s => s.autoGenerated)
    }

    getTopSkills(limit = 10): Skill[] {
        return this.getAllSkills()
            .sort((a, b) => b.usageCount - a.usageCount)
            .slice(0, limit)
    }

    // ============================================
    // Statistics
    // ============================================

    getStats(): {
        totalSkills: number
        autoGenerated: number
        manual: number
        totalUsage: number
        avgSuccessRate: number
    } {
        const skills = this.getAllSkills()
        const totalUsage = skills.reduce((sum, s) => sum + s.usageCount, 0)
        const avgSuccessRate = skills.length > 0
            ? skills.reduce((sum, s) => sum + s.successRate, 0) / skills.length
            : 0

        return {
            totalSkills: skills.length,
            autoGenerated: skills.filter(s => s.autoGenerated).length,
            manual: skills.filter(s => !s.autoGenerated).length,
            totalUsage,
            avgSuccessRate,
        }
    }

    // ============================================
    // Persistence
    // ============================================

    exportToJSON(): string {
        return JSON.stringify({
            skills: Array.from(this.skills.entries()),
        }, null, 2)
    }

    importFromJSON(json: string): void {
        try {
            const data = JSON.parse(json)
            if (data.skills) {
                this.skills = new Map(data.skills)

                // Rebuild trigger index
                this.skillsByTrigger.clear()
                for (const skill of this.skills.values()) {
                    for (const trigger of skill.triggers) {
                        this.skillsByTrigger.set(trigger, skill.id)
                    }
                }
            }
            console.log(`[Nova Skills] Imported ${this.skills.size} skills`)
        } catch (err) {
            console.error('[Nova Skills] Failed to import:', err)
        }
    }
}

// ============================================
// Factory
// ============================================

export function createSkillGenerator(): SkillGenerator {
    return new SkillGenerator()
}

export default { SkillGenerator, createSkillGenerator }
