/**
 * Zustell-Port des Planers (Phase 1, CL-09).
 *
 * The planner never talks to Telegram, the dashboard or the card layer
 * directly. Everything it wants to say (briefings, thoughts, job results)
 * leaves through ONE port that the Main wires at startup:
 *
 *   import { setPlannerDeliveryPort } from './planner/delivery-port.js'
 *   setPlannerDeliveryPort({ name: 'telegram-karten', deliver: async msg => { ...; return { status: 'zugestellt' } } })
 *
 * Contract for a port implementation:
 * - return `{ status: 'zugestellt' }` (or nothing) only after the message
 *   really left the node; the planner then logs it and never sends it again;
 * - throw a FenceError (src/mesh/fence.ts) when this node has no live
 *   Main/Telegram authority: the message stays pending, no attempt is counted;
 * - return `{ status: 'kein-port' }` when the channel is not connected yet:
 *   pending, no attempt counted;
 * - throw or return `{ status: 'fehler' }` for a real failure: counted, given
 *   up after 5 attempts.
 * - `permission` / `thoughtId` let the card layer decide on buttons: a thought
 *   with permission 'fragen' may get [Ja] [Nein] [Später]; 'nie' never gets a
 *   button. The ticket for a button is created by the card layer's code, never
 *   by the planner or a model.
 *
 * No port wired = every delivery is `kein-port` and stays pending (nothing is
 * dropped silently, nothing is sent from a worker).
 */

import { isFenceError } from '../mesh/fence.js'
import { redactSecrets } from '../security/secret-redaction.js'

export type OutgoingKind = 'erinnerung' | 'briefing' | 'gedanke' | 'job'
export type OutgoingUrgency = 'dringend' | 'normal'
export type OutgoingPermission = 'selbst' | 'fragen' | 'nie'

export interface PlannerOutgoing {
    /** Delivery id, generated by the planner (`out-<12 hex>`). */
    id: string
    kind: OutgoingKind
    title: string
    /** Plain German text, already redacted (reminders: the user's own text). */
    text: string
    urgency: OutgoingUrgency
    createdAt: string
    /** Reminders: the original requester; otherwise the owner channel. */
    target?: { userId: string; channel: string }
    jobId?: string
    slot?: string
    thoughtId?: string
    permission?: OutgoingPermission
    /** Thought ids referenced by a briefing. */
    refs?: string[]
    /** A pending delivery after this instant is logged as `verfallen`, not sent. */
    expiresAt?: string
    /** Paket L: briefing sections for the paged Telegram view (one button per section). */
    sections?: Array<{ titel: string; zeilen: string[] }>
    /** Paket L: traffic light + one sentence. */
    kopf?: string
}

export type OutgoingDraft = Omit<PlannerOutgoing, 'id' | 'createdAt' | 'jobId' | 'slot'>

export type DeliveryStatus = 'zugestellt' | 'fence' | 'kein-port' | 'fehler'
export interface DeliveryReceipt {
    status: DeliveryStatus
    detail?: string
    /** Optional id of the sent message (e.g. Telegram message id) for later edits. */
    ref?: string
}

export interface DeliveryPort {
    readonly name: string
    deliver(message: PlannerOutgoing): Promise<DeliveryReceipt | void>
}

let currentPort: DeliveryPort | null = null

/** Wired once by the Main (Telegram cards, dashboard feed, ...). */
export function setPlannerDeliveryPort(port: DeliveryPort | null): void {
    currentPort = port
}

export function getPlannerDeliveryPort(): DeliveryPort | null {
    return currentPort
}

const CONTROL = /[\u0000-\u0008\u000b-\u001f\u007f]/g

export function cleanText(value: unknown, max = 4000): string {
    return redactSecrets(String(value ?? '')).replace(CONTROL, ' ').slice(0, max)
}

/** Never throws. Maps every port behaviour onto a receipt. */
export async function deliverVia(port: DeliveryPort | null | undefined, message: PlannerOutgoing): Promise<DeliveryReceipt> {
    if (!port) return { status: 'kein-port', detail: 'kein Zustell-Port verdrahtet' }
    const safe: PlannerOutgoing = message.kind === 'erinnerung'
        ? message
        : { ...message, title: cleanText(message.title, 200), text: cleanText(message.text) }
    try {
        const receipt = await port.deliver(safe)
        if (!receipt) return { status: 'zugestellt' }
        const status: DeliveryStatus = ['zugestellt', 'fence', 'kein-port', 'fehler'].includes(receipt.status) ? receipt.status : 'fehler'
        return { status, detail: receipt.detail ? cleanText(receipt.detail, 200) : undefined, ref: receipt.ref ? String(receipt.ref).slice(0, 100) : undefined }
    } catch (error) {
        if (isFenceError(error)) return { status: 'fence', detail: cleanText((error as Error).message, 200) }
        return { status: 'fehler', detail: cleanText((error as Error)?.message || error, 200) }
    }
}
