/**
 * Planer (Phase 1, CL-09 "ein Planer nach Hermes-Muster").
 *
 * One job list for everything time-based: reminders, morning/evening
 * briefing, Nachtwache, later scout and idea runs. Each job has an execution
 * log and a delivery log (JSONL, one line per event).
 *
 * Files (under the data directory):
 *   planner/jobs.json        { version: 1, jobs: PlannerJob[] }   atomic write
 *   planner/runs.jsonl       one line per execution  (PlannerRunLogEntry)
 *   planner/deliveries.jsonl one line per delivery attempt (PlannerDeliveryLogEntry)
 *   planner/lease.json       which process on this data dir may tick
 *
 * Guarantees:
 * - A due job runs once per slot. Before the handler runs, a claim is
 *   persisted; a restart that finds a claim without result logs the slot as
 *   `unterbrochen` and moves on (no double run).
 * - The produced message is kept as `pending` until a port confirms it; the
 *   delivery log is the idempotency record (`jobId@slot` zugestellt = never
 *   again), so a crash between delivery and bookkeeping does not resend.
 * - Delivering jobs (and `mainOnly` jobs) run only when `authority()` says
 *   this process is the fenced Main. Workers never deliver. A FenceError or a
 *   missing port keeps the message pending without counting an attempt.
 * - A non-delivering job cannot send: its outgoing draft is ignored.
 * - Job and delivery ids are generated by code, never taken from callers.
 */

import { createHash, randomBytes } from 'node:crypto'
import { appendFileSync, existsSync, mkdirSync, readFileSync, renameSync, statSync } from 'node:fs'
import { join } from 'node:path'
import { atomicWriteJsonSync } from '../core/atomic-storage.js'
import { cleanText, deliverVia, getPlannerDeliveryPort, type DeliveryPort, type OutgoingDraft, type PlannerOutgoing } from './delivery-port.js'
import { deliverPendingThoughts, type ThoughtStore } from './thoughts.js'
import { DEFAULT_TIME_ZONE, HHMM_PATTERN, isValidTimeZone, nextDailySlot } from './time.js'

export type JobSchedule =
    | { type: 'einmal'; at: string }
    | { type: 'taeglich'; time: string; timeZone?: string }
    | { type: 'intervall'; minutes: number }

export type JobStatus = 'aktiv' | 'erledigt' | 'aufgegeben'

export interface PlannerJob {
    id: string
    kind: string
    title: string
    schedule: JobSchedule
    delivers: boolean
    mainOnly: boolean
    enabled: boolean
    payload: Record<string, unknown>
    status: JobStatus
    createdAt: string
    updatedAt: string
    /** Next due slot (ISO); null when a one-shot job is done. */
    nextRunAt: string | null
    lastRunAt?: string
    lastStatus?: string
    runs: number
    /** Daily jobs: a slot later than this is logged as `verpasst`. */
    maxLateMinutes?: number
    /** Delivering jobs: pending message expires this many minutes after its slot. */
    expiresAfterMinutes?: number
    claim?: { slot: string; runId: string; at: string }
    pending?: { slot: string; outgoing: PlannerOutgoing; attempts: number; firstTriedAt: string }
}

export interface NewJob {
    kind: string
    title: string
    schedule: JobSchedule
    delivers?: boolean
    mainOnly?: boolean
    enabled?: boolean
    payload?: Record<string, unknown>
    /** Deterministic id source (e.g. a migrated reminder id): same key = same job. */
    idKey?: string
    maxLateMinutes?: number
    expiresAfterMinutes?: number
}

export interface SystemJob extends NewJob { id: string }

export interface JobContext { now: number; slot: string; isMain: boolean }
export interface JobRunResult { summary: string; ok?: boolean; outgoing?: OutgoingDraft }
export interface JobHandler {
    run(job: PlannerJob, ctx: JobContext): Promise<JobRunResult>
    afterDelivery?(job: PlannerJob, outgoing: PlannerOutgoing, ctx: JobContext): Promise<void> | void
    afterGiveUp?(job: PlannerJob, outgoing: PlannerOutgoing, ctx: JobContext): Promise<void> | void
}

export interface PlannerRunLogEntry {
    at: string
    runId: string
    jobId: string
    kind: string
    slot: string
    node: string
    ergebnis: 'ok' | 'fehler' | 'unterbrochen' | 'verpasst' | 'kein-handler'
    summary: string
    ms?: number
}

export interface PlannerDeliveryLogEntry {
    at: string
    deliveryId: string
    kind: string
    port: string
    status: string
    node: string
    jobId?: string
    slot?: string
    thoughtId?: string
    attempt?: number
    detail?: string
}

export interface TickReport {
    lease: boolean
    isMain: boolean
    executed: string[]
    delivered: string[]
    deferred: string[]
    skippedWorker: string[]
    thoughts?: { sent: number; held: number; limited: number; failed: number }
}

export interface PlannerDeps {
    dataDir: string
    now?: () => number
    /** True only on the fenced Main. Default: false (fail closed). */
    authority?: () => boolean | Promise<boolean>
    nodeId?: string
    instanceId?: string
    ports?: { default?: () => DeliveryPort | null; byKind?: Partial<Record<PlannerOutgoing['kind'], DeliveryPort>> }
    thoughts?: ThoughtStore
    /** Held-back thoughts go into the next briefing (instead of waiting). */
    briefingEnabled?: () => boolean
    maxAttempts?: number
    leaseMs?: number
}

export interface Planner {
    readonly paths: { dir: string; jobs: string; runs: string; deliveries: string; lease: string }
    register(kind: string, handler: JobHandler): void
    addJob(input: NewJob): PlannerJob
    upsertSystemJob(input: SystemJob): PlannerJob
    getJob(id: string): PlannerJob | null
    listJobs(filter?: { kind?: string; status?: JobStatus }): PlannerJob[]
    setEnabled(id: string, enabled: boolean): PlannerJob | null
    completeJob(id: string, lastStatus: string): PlannerJob | null
    tick(): Promise<TickReport>
    start(intervalMs: number): void
    stop(): void
}

export const JOB_ID_PATTERN = /^(?:job-[a-f0-9]{12}|sys-[a-z0-9-]{2,40})$/
const KIND_PATTERN = /^[a-z][a-z0-9-]{1,40}$/
const MAX_LOG_BYTES = 5 * 1024 * 1024
const MAX_FINISHED_JOBS = 200

export function validateSchedule(raw: JobSchedule): JobSchedule {
    if (!raw || typeof raw !== 'object') throw new Error('Zeitplan fehlt')
    if (raw.type === 'einmal') {
        const at = Date.parse(String(raw.at))
        if (!Number.isFinite(at)) throw new Error('Ungültiger Zeitpunkt')
        return { type: 'einmal', at: new Date(at).toISOString() }
    }
    if (raw.type === 'taeglich') {
        if (!HHMM_PATTERN.test(String(raw.time))) throw new Error('Uhrzeit muss HH:MM sein')
        const timeZone = raw.timeZone && isValidTimeZone(raw.timeZone) ? raw.timeZone : DEFAULT_TIME_ZONE
        return { type: 'taeglich', time: raw.time, timeZone }
    }
    if (raw.type === 'intervall') {
        const minutes = Math.floor(Number(raw.minutes))
        if (!Number.isFinite(minutes) || minutes < 1 || minutes > 7 * 24 * 60) throw new Error('Intervall 1..10080 Minuten')
        return { type: 'intervall', minutes }
    }
    throw new Error('Unbekannter Zeitplan')
}

/** First due slot of a fresh (or re-scheduled) job. */
export function firstSlot(schedule: JobSchedule, now: number): number {
    if (schedule.type === 'einmal') return Date.parse(schedule.at)
    if (schedule.type === 'taeglich') return nextDailySlot(now - 1, schedule.time, schedule.timeZone)
    return now
}

/** Slot after a finished run; null = one-shot done. Missed slots are skipped, never replayed in a burst. */
export function followingSlot(schedule: JobSchedule, now: number): number | null {
    if (schedule.type === 'einmal') return null
    if (schedule.type === 'taeglich') return nextDailySlot(now, schedule.time, schedule.timeZone)
    return now + schedule.minutes * 60_000
}

const hex = () => randomBytes(6).toString('hex')

export function createPlanner(deps: PlannerDeps): Planner {
    const now = deps.now ?? Date.now
    const dir = join(deps.dataDir, 'planner')
    const paths = { dir, jobs: join(dir, 'jobs.json'), runs: join(dir, 'runs.jsonl'), deliveries: join(dir, 'deliveries.jsonl'), lease: join(dir, 'lease.json') }
    const instanceId = deps.instanceId ?? `${process.pid}-${hex()}`
    const nodeId = cleanText(deps.nodeId ?? 'lokal', 64)
    const maxAttempts = deps.maxAttempts ?? 5
    const leaseMs = deps.leaseMs ?? 120_000
    const handlers = new Map<string, JobHandler>()
    let ticking = false
    let timer: ReturnType<typeof setInterval> | null = null
    const iso = (t = now()) => new Date(t).toISOString()

    const load = (): PlannerJob[] => {
        try {
            const raw = JSON.parse(readFileSync(paths.jobs, 'utf8'))
            return Array.isArray(raw?.jobs) ? raw.jobs.filter((job: PlannerJob) => job && JOB_ID_PATTERN.test(job.id)) : []
        } catch { return [] }
    }
    const save = (jobs: PlannerJob[]) => {
        const finished = jobs.filter(job => job.status !== 'aktiv').sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
        const dropped = new Set(finished.slice(MAX_FINISHED_JOBS).map(job => job.id))
        mkdirSync(dir, { recursive: true, mode: 0o700 })
        atomicWriteJsonSync(paths.jobs, { version: 1, jobs: jobs.filter(job => !dropped.has(job.id)) })
    }
    // Synchronous read-modify-write; never hold a job array across an await.
    const mutate = <T>(fn: (jobs: PlannerJob[]) => T): T => {
        const jobs = load()
        const result = fn(jobs)
        save(jobs)
        return result
    }
    const append = (file: string, entry: object) => {
        try {
            mkdirSync(dir, { recursive: true, mode: 0o700 })
            if (existsSync(file) && statSync(file).size > MAX_LOG_BYTES) renameSync(file, `${file}.1`)
            appendFileSync(file, `${JSON.stringify(entry)}\n`, { mode: 0o600 })
        } catch (error) {
            console.warn('[Planer] Protokoll nicht schreibbar:', (error as Error)?.message)
        }
    }
    const logRun = (entry: PlannerRunLogEntry) => append(paths.runs, { ...entry, summary: cleanText(entry.summary, 300) })
    const logDelivery = (entry: Omit<PlannerDeliveryLogEntry, 'node'>) => append(paths.deliveries, { ...entry, node: nodeId })

    const deliveredKeys = (): Set<string> => {
        const keys = new Set<string>()
        for (const file of [`${paths.deliveries}.1`, paths.deliveries]) {
            if (!existsSync(file)) continue
            for (const line of readFileSync(file, 'utf8').split('\n')) {
                if (!line.includes('"zugestellt"')) continue
                try {
                    const entry = JSON.parse(line)
                    if (entry.status === 'zugestellt' && entry.jobId && entry.slot) keys.add(`${entry.jobId}@${entry.slot}`)
                } catch { /* corrupt line */ }
            }
        }
        return keys
    }

    const acquireLease = (): boolean => {
        const t = now()
        try {
            const current = JSON.parse(readFileSync(paths.lease, 'utf8'))
            if (current?.owner && current.owner !== instanceId && Number(current.until) > t) return false
        } catch { /* free */ }
        try {
            mkdirSync(dir, { recursive: true, mode: 0o700 })
            atomicWriteJsonSync(paths.lease, { owner: instanceId, node: nodeId, until: t + leaseMs })
            return JSON.parse(readFileSync(paths.lease, 'utf8'))?.owner === instanceId
        } catch { return false }
    }
    const releaseLease = () => {
        try {
            const current = JSON.parse(readFileSync(paths.lease, 'utf8'))
            if (current?.owner === instanceId) atomicWriteJsonSync(paths.lease, { owner: instanceId, node: nodeId, until: 0 })
        } catch { /* nothing held */ }
    }

    const getJob = (id: string) => load().find(job => job.id === id) ?? null

    /** Close the slot and move to the next one. No-op if the slot already moved. */
    const finalize = (id: string, slot: string, lastStatus: string) => mutate(jobs => {
        const job = jobs.find(entry => entry.id === id)
        if (!job || job.nextRunAt !== slot) return
        const t = now()
        job.claim = undefined
        job.pending = undefined
        job.runs = (job.runs || 0) + 1
        job.lastRunAt = iso(t)
        job.lastStatus = lastStatus
        job.updatedAt = iso(t)
        const next = followingSlot(job.schedule, t)
        if (next === null) {
            job.nextRunAt = null
            job.status = lastStatus === 'aufgegeben' ? 'aufgegeben' : 'erledigt'
        } else {
            job.nextRunAt = iso(next)
        }
    })

    const resolveAuthority = async (): Promise<boolean> => {
        if (!deps.authority) return false
        try { return Boolean(await deps.authority()) } catch { return false }
    }
    const defaultPort = () => (deps.ports?.default ? deps.ports.default() : getPlannerDeliveryPort())

    const deliverPending = async (id: string, ctx: JobContext, report: TickReport) => {
        const job = getJob(id)
        if (!job?.pending) return
        const { slot, outgoing } = job.pending
        const handler = handlers.get(job.kind)
        if (deliveredKeys().has(`${job.id}@${slot}`)) {
            finalize(job.id, slot, 'zugestellt')
            return
        }
        if (outgoing.expiresAt && ctx.now > Date.parse(outgoing.expiresAt)) {
            logDelivery({ at: iso(), deliveryId: outgoing.id, kind: outgoing.kind, port: '-', status: 'verfallen', jobId: job.id, slot })
            finalize(job.id, slot, 'verfallen')
            return
        }
        const port = deps.ports?.byKind?.[outgoing.kind] ?? defaultPort()
        const receipt = await deliverVia(port, outgoing)
        const attempt = job.pending.attempts + 1
        logDelivery({ at: iso(), deliveryId: outgoing.id, kind: outgoing.kind, port: port?.name ?? 'keiner', status: receipt.status, jobId: job.id, slot, attempt, detail: receipt.detail })
        if (receipt.status === 'zugestellt') {
            report.delivered.push(job.id)
            try { await handler?.afterDelivery?.(job, outgoing, ctx) } catch (error) { console.warn(`[Planer] Nacharbeit ${job.id}:`, (error as Error)?.message) }
            finalize(job.id, slot, 'zugestellt')
            return
        }
        report.deferred.push(job.id)
        if (receipt.status === 'fence' || receipt.status === 'kein-port') return
        if (attempt >= maxAttempts) {
            try { await handler?.afterGiveUp?.(job, outgoing, ctx) } catch (error) { console.warn(`[Planer] Aufgabe ${job.id}:`, (error as Error)?.message) }
            finalize(job.id, slot, 'aufgegeben')
            return
        }
        mutate(jobs => {
            const entry = jobs.find(item => item.id === job.id)
            if (entry?.pending && entry.pending.slot === slot) entry.pending.attempts = attempt
        })
    }

    const processJob = async (id: string, isMain: boolean, report: TickReport) => {
        const job = getJob(id)
        if (!job || !job.nextRunAt) return
        const slot = job.nextRunAt
        const ctx: JobContext = { now: now(), slot, isMain }
        if (job.pending && job.pending.slot === slot) {
            await deliverPending(id, ctx, report)
            return
        }
        if (job.claim && job.claim.slot === slot) {
            logRun({ at: iso(), runId: job.claim.runId, jobId: job.id, kind: job.kind, slot, node: nodeId, ergebnis: 'unterbrochen', summary: 'Lauf durch Neustart unterbrochen; nicht wiederholt (kein Doppel).' })
            finalize(job.id, slot, 'unterbrochen')
            return
        }
        const lateMs = ctx.now - Date.parse(slot)
        if (job.schedule.type === 'taeglich' && job.maxLateMinutes && lateMs > job.maxLateMinutes * 60_000) {
            logRun({ at: iso(), runId: `run-${hex()}`, jobId: job.id, kind: job.kind, slot, node: nodeId, ergebnis: 'verpasst', summary: `${Math.round(lateMs / 60_000)} min zu spät, nicht nachgeholt.` })
            finalize(job.id, slot, 'verpasst')
            return
        }
        const handler = handlers.get(job.kind)
        const runId = `run-${hex()}`
        if (!handler) {
            logRun({ at: iso(), runId, jobId: job.id, kind: job.kind, slot, node: nodeId, ergebnis: 'kein-handler', summary: `Kein Handler für ${job.kind}.` })
            finalize(job.id, slot, 'kein-handler')
            return
        }
        mutate(jobs => {
            const entry = jobs.find(item => item.id === job.id)
            if (entry) entry.claim = { slot, runId, at: iso() }
        })
        const started = now()
        let result: JobRunResult
        try {
            result = await handler.run(job, ctx)
        } catch (error) {
            result = { ok: false, summary: `Fehler: ${(error as Error)?.message || error}` }
        }
        const ok = result?.ok !== false
        logRun({ at: iso(), runId, jobId: job.id, kind: job.kind, slot, node: nodeId, ergebnis: ok ? 'ok' : 'fehler', summary: String(result?.summary ?? ''), ms: now() - started })
        report.executed.push(job.id)
        if (!(result?.outgoing && job.delivers)) {
            finalize(job.id, slot, ok ? 'ok' : 'fehler')
            return
        }
        const outgoing: PlannerOutgoing = {
            ...result.outgoing,
            id: `out-${hex()}`,
            jobId: job.id,
            slot,
            createdAt: iso(),
            ...(job.expiresAfterMinutes ? { expiresAt: iso(Date.parse(slot) + job.expiresAfterMinutes * 60_000) } : {}),
        }
        mutate(jobs => {
            const entry = jobs.find(item => item.id === job.id)
            if (!entry || entry.nextRunAt !== slot) return
            entry.claim = undefined
            entry.pending = { slot, outgoing, attempts: 0, firstTriedAt: iso() }
            entry.updatedAt = iso()
        })
        await deliverPending(job.id, ctx, report)
    }

    const planner: Planner = {
        paths,
        register(kind, handler) {
            if (!KIND_PATTERN.test(kind)) throw new Error(`Ungültige Job-Art: ${kind}`)
            handlers.set(kind, handler)
        },
        addJob(input) {
            if (!KIND_PATTERN.test(String(input?.kind))) throw new Error(`Ungültige Job-Art: ${String(input?.kind).slice(0, 40)}`)
            const schedule = validateSchedule(input.schedule)
            const id = input.idKey ? `job-${createHash('sha256').update(String(input.idKey)).digest('hex').slice(0, 12)}` : `job-${hex()}`
            return mutate(jobs => {
                const existing = jobs.find(job => job.id === id)
                if (existing) return existing
                const t = now()
                const delivers = input.delivers === true
                const job: PlannerJob = {
                    id, kind: input.kind, title: cleanText(input.title, 200), schedule,
                    delivers, mainOnly: delivers || input.mainOnly === true, enabled: input.enabled !== false,
                    payload: input.payload && typeof input.payload === 'object' ? input.payload : {},
                    status: 'aktiv', createdAt: iso(t), updatedAt: iso(t), nextRunAt: iso(firstSlot(schedule, t)), runs: 0,
                    ...(input.maxLateMinutes ? { maxLateMinutes: Math.floor(input.maxLateMinutes) } : {}),
                    ...(input.expiresAfterMinutes ? { expiresAfterMinutes: Math.floor(input.expiresAfterMinutes) } : {}),
                }
                jobs.push(job)
                return job
            })
        },
        upsertSystemJob(input) {
            if (!/^sys-[a-z0-9-]{2,40}$/.test(String(input?.id))) throw new Error('System-Jobs brauchen eine feste sys-ID')
            if (!KIND_PATTERN.test(String(input.kind))) throw new Error(`Ungültige Job-Art: ${input.kind}`)
            const schedule = validateSchedule(input.schedule)
            return mutate(jobs => {
                const t = now()
                const delivers = input.delivers === true
                const enabled = input.enabled !== false
                const existing = jobs.find(job => job.id === input.id)
                if (!existing) {
                    const job: PlannerJob = {
                        id: input.id, kind: input.kind, title: cleanText(input.title, 200), schedule,
                        delivers, mainOnly: delivers || input.mainOnly === true, enabled,
                        payload: input.payload ?? {}, status: 'aktiv', createdAt: iso(t), updatedAt: iso(t),
                        nextRunAt: iso(firstSlot(schedule, t)), runs: 0,
                        ...(input.maxLateMinutes ? { maxLateMinutes: Math.floor(input.maxLateMinutes) } : {}),
                        ...(input.expiresAfterMinutes ? { expiresAfterMinutes: Math.floor(input.expiresAfterMinutes) } : {}),
                    }
                    jobs.push(job)
                    return job
                }
                const scheduleChanged = JSON.stringify(existing.schedule) !== JSON.stringify(schedule)
                const reEnabled = enabled && !existing.enabled
                existing.kind = input.kind
                existing.title = cleanText(input.title, 200)
                existing.schedule = schedule
                existing.delivers = delivers
                existing.mainOnly = delivers || input.mainOnly === true
                existing.enabled = enabled
                existing.payload = input.payload ?? existing.payload ?? {}
                existing.maxLateMinutes = input.maxLateMinutes ? Math.floor(input.maxLateMinutes) : undefined
                existing.expiresAfterMinutes = input.expiresAfterMinutes ? Math.floor(input.expiresAfterMinutes) : undefined
                if (scheduleChanged || reEnabled || existing.status !== 'aktiv') {
                    existing.status = 'aktiv'
                    existing.nextRunAt = iso(firstSlot(schedule, t))
                    existing.pending = undefined
                    existing.claim = undefined
                }
                existing.updatedAt = iso(t)
                return existing
            })
        },
        getJob,
        listJobs(filter = {}) {
            return load().filter(job => (!filter.kind || job.kind === filter.kind) && (!filter.status || job.status === filter.status))
        },
        setEnabled(id, enabled) {
            return mutate(jobs => {
                const job = jobs.find(entry => entry.id === id)
                if (!job) return null
                job.enabled = enabled
                job.updatedAt = iso()
                return job
            })
        },
        completeJob(id, lastStatus) {
            return mutate(jobs => {
                const job = jobs.find(entry => entry.id === id)
                if (!job) return null
                job.status = 'erledigt'
                job.nextRunAt = null
                job.pending = undefined
                job.claim = undefined
                job.lastStatus = cleanText(lastStatus, 64)
                job.updatedAt = iso()
                return job
            })
        },
        async tick() {
            const report: TickReport = { lease: false, isMain: false, executed: [], delivered: [], deferred: [], skippedWorker: [] }
            if (ticking) return report
            ticking = true
            try {
                if (!acquireLease()) return report
                report.lease = true
                report.isMain = await resolveAuthority()
                const t = now()
                const due = load()
                    .filter(job => job.enabled && job.status === 'aktiv' && job.nextRunAt && Date.parse(job.nextRunAt) <= t)
                    .sort((a, b) => Date.parse(a.nextRunAt!) - Date.parse(b.nextRunAt!))
                for (const job of due) {
                    if ((job.delivers || job.mainOnly) && !report.isMain) {
                        report.skippedWorker.push(job.id)
                        continue
                    }
                    try {
                        await processJob(job.id, report.isMain, report)
                    } catch (error) {
                        console.warn(`[Planer] Job ${job.id} fehlgeschlagen:`, (error as Error)?.message)
                    }
                }
                if (report.isMain && deps.thoughts) {
                    report.thoughts = await deliverPendingThoughts(deps.thoughts, defaultPort(), {
                        now: now(),
                        briefingEnabled: deps.briefingEnabled?.() === true,
                        log: entry => logDelivery({ at: entry.at, deliveryId: entry.deliveryId, kind: entry.kind, port: entry.port, status: entry.status, thoughtId: entry.thoughtId, detail: entry.detail }),
                    })
                }
                return report
            } finally {
                ticking = false
            }
        },
        start(intervalMs) {
            if (timer) return
            timer = setInterval(() => { void planner.tick().catch(error => console.warn('[Planer] Tick fehlgeschlagen:', (error as Error)?.message)) }, Math.max(5_000, intervalMs))
            timer.unref?.()
        },
        stop() {
            if (timer) clearInterval(timer)
            timer = null
            releaseLease()
        },
    }
    return planner
}
